[build]
  base = "client"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18.0.0"  # Recommended LTS version for CRA
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# Required for Create React App SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

