[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.17.0"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
