[build]
  base = "client"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "client/.next"

[build.environment]
  NODE_VERSION = "20.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "false"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Required for Next.js SPAs
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
