[build]
  base = "."
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && npm start"
  port = 3000
  publish = "client/build"
