[build]
  base = "."
  publish = "client/build"
  command = "cd client && npm install --legacy-peer-deps && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18.17.1"  # Specific LTS version
  NPM_VERSION = "9.6.7"     # Specific NPM version
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "false"
  # Update with your actual API URL
  REACT_APP_API_URL = "https://your-api-url.railway.app"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache settings (optional)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
